name: "Build & Push mdshack/dnsmasq:latest"

on:
  push:
    branches: [main]
    paths: [dnsmasq/**]

jobs:
  build_and_push:
    uses: mdshack/docker-images/.github/workflows/build-image.yaml@main
    with: 
      path: ./dnsmasq
      repository: mdshack/dnsmasq
      tag: latest
    secrets: inherit
