name: Build & Push Docker Image

on:
  workflow_call:
    inputs: 
      path:
        type: string
        required: true
        description: Docker image context
      repository:
        type: string
        required: true
        description: DockerHub image repo name
      tag:
        type: string
        required: true
        description: DockerHub image tag

  workflow_dispatch:
    inputs: 
      path:
        type: string
        required: true
        description: Docker image context
      repository:
        type: string
        required: true
        description: DockerHub image repo name
      tag:
        type: string
        required: true
        description: DockerHub image tag

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ github.event.inputs.repository }}:${{ github.event.inputs.tag }}
          context: ${{ github.event.inputs.path }}